In [1]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import random
from scipy.optimize import curve_fit
plt.rcParams["font.family"] = "Arial"
plt.rcParams["font.size"] = 11

Os alunos de um curso de pós graduação decidiram verificar qual se os diferentes grupos de pesquisa consumiam a mesma quantidade de café por mês. 

A quantidade de cafézinhos foi obtida através de comprovantes; ou seja, apenas cafés de um mesmo local.



In [38]:
random.seed(42)
random_value = random.random()

random.seed(31416)
random_value2 = random.random()

rese_1 = np.array([84.99, 84.04, 84.38])/random_value

rese_2 = np.array([85.15, 85.13, 84.88])/random_value

rese_3 = np.array([84.72, 84.48, 85.16])/random_value

rese_4 = np.array([84.20, 84.10, 84.55])/random_value
rese_4

array([131.68043661, 131.52404654, 132.22780184])

In [34]:
stats.levene(rese_1, rese_2, rese_3, rese_4)

LeveneResult(statistic=0.8446642426619849, pvalue=0.5069791802873922)

In [39]:
rese_1

array([132.91591814, 131.4302125 , 131.96193873])

In [40]:
rese_2

array([133.16614225, 133.13486423, 132.74388907])

In [41]:
rese_3

array([132.49366496, 132.1183288 , 133.18178125])

In [42]:
rese_4

array([131.68043661, 131.52404654, 132.22780184])